---
title: "Tables and Figures"
output: pdf_document
date: \today
header-includes: 
 - \usepackage{bbm}
 - \usepackage{unicode}
 - \usepackage{hyperref}
 - \hypersetup{colorlinks=true,citecolor=purple,linkcolor=purple,linktocpage=true, urlcolor=purple}
 - \usepackage[labelformat=empty]{caption}
 - \usepackage{xcolor}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	echo = FALSE,
	cache = FALSE,
	collapse = TRUE
)
```

```{r source_calls, message=FALSE}
source("R.R")
```

```{r load_data}
cmr <- read_csv("cmr.csv")
```

```{r first_look, include=FALSE}
# First look at the data 
# See what changes we need to make 
dplyr::glimpse(cmr) # notice: lots of options for 'clinic', and some categories are labeled as numbers! 
table(cmr$Clinic, useNA = "always") # hmmm... need to combine some categories 

```

```{r data_prep}
# Make some formatting changes
cmr <- cmr %>%
  # collapse categories for clinic (we will need this for analysis)
  mutate(Clinic = if_else(Clinic %in% c("ADMS", "CCST", "CODHDG", "FEECLS", 
                                        "GMU", "HDGEN", "HDPROS", "LTDCAR"),
                          "Other",
                          Clinic),
         # tell the computer that 'No_surface' numbers represent *categories* 
         No_Surfaces = as.character(No_Surfaces),
         # tell the computer that RCT is a yes/no outcome
         RCT = case_when(
           RCT == 0 ~  "No RCT",
           RCT == 1 ~ "RCT"),
         # make the IDs have readable names 
         RecordID = paste0("Patient ", RecordID),
         # Represent the outcome (reintervention) in both numbers and words
         Event = Status, 
         Status = case_when(
           Event == 0 ~ "Censored",
           Event == 1 ~ "Event")) 

```

# Tables 

```{r word_bank, warning=FALSE}
# silence warning: it is related to the color choices for the word bank 
word_bank <- tibble(terms = c("Observation", "Time", "Event", "Censored",
                              "Survival time", "Median survival time",
                              "Nth year survival", "Kaplan-Meier plot",
                              "Hazard ratio","Log-rank test","Cox model"
                              ),
                    # goal for self: word limit on definitions = 10 words  
                    defs = c("Unit of study",
                             "Time since entry into study",
                             "Occasion that marks the outcome",
                             "No event was observed",
                             "Time elapsed until event/censored",
                             "Time when about half of observations had events",
                             "Proportion of observations still 'alive' year N",
                             "Curves that tell the story",
                             "Measure for comparing probability of 'event'",
                             "Tool for comparing groups without controlling for other factors",
                             "Tool for comparing groups while controlling for other factors"
                             ))

(word_bank %>%
  kable(booktabs=T,
      linesep="",
      col.names = c("Terms", "Brief definition"),
      caption = "Table 1: Word Bank") %>% 
  kable_paper(full_width=F) %>%
  column_spec(1:2,
              color=c(rep(c("#440154", "#21918c"), 5), "#440154"))) %>%
  kable_styling(latex_options = c("HOLD_position"))
              # background = spec_color(1:5, alpha = 0.5)))

```

```{r descriptives}
table1_labels <- list(
  Age ~ "Age (yrs)",
  Gender ~ "Sex",
  CRA ~ "CRA",
  Tooth_Type ~ "Tooth type",
  Jaw ~ "Jaw",
  Repair_Material ~ "Repair material",
  Surfaces ~ "Surfaces",
  No_Surfaces ~ "Number of surfaces",
  RCT ~ "Root canal treated?",
  Crown_Type ~ "Crown type",
  # Clinic ~ "Clinic",
  Provider_Type ~ "Provider"
)

table1 <- tbl_summary(data = cmr %>%
                    dplyr::select(-c(RecordID, Event, No_Cases, Tooth_Number,
                                     Clinic, Date_Repair, End_Date, Failure_Date,
                                     Failure, Last_exam, Failure_Reason)),
            # digits = everything() ~ 2,
            label = table1_labels,
            statistic = list(
              all_continuous() ~ "{median} ({min}, {max})",
              all_categorical() ~ "{n} ({p}%)")) %>% 
  bold_labels() %>%
  modify_footnote(update = all_stat_cols() ~ "Formats: Median (range), n (%)",
                  abbreviation = FALSE)
  


table1 %>%
  as_kable_extra(format = "latex", 
                 booktabs = TRUE,
                 caption = "Table 2: Description of data",
                 longtable = TRUE) %>%
  kable_styling(latex_options = c("striped", "repeat_header", "HOLD_position"))


```

```{r median_survival}
# calculate median survival with the KM method 
s1 <- survfit(Surv(Time, Event) ~ 1, data = cmr) 

# create a table with the median survival time and its accompanying 95% confidence interval
s1_median <- summary(s1)$table

s1_median[c("median", "0.95LCL", "0.95UCL")] %>%
  t() %>%
 kable(digits = 2,
       col.names = c(
         "Median survival time",
         "95% CI (lower)",
         "95% CI (upper)"
       ),
       caption = "Table 3: Median survival time",
       format = "latex",
       booktabs = TRUE) %>%
  kable_styling(latex_options = c("HOLD_position"))
```

```{r nth_year_survival}
# 1, 3, and 5 year survival -----------------------------------------------
five_yr_surv <- summary(survfit(Surv(Time, Event) ~ 1, data = cmr), times = c(1, 3, 5))

five_yr_surv_table <- nth_year_survival(five_yr_surv)

five_yr_surv_table %>% 
  kable(digits = 3,
        format = "latex",
        caption = "Table 4: 1, 3, and 5 year survival",
        booktabs = TRUE) %>%
  kable_styling(latex_options = c("HOLD_position", "scale_down")) %>%
  kable_paper(full_width=F) %>%
  column_spec(1:ncol(five_yr_surv_table),
              color=c("#440154", "#21918c", "#5ec962"))
              # background = spec_color(1:nrow(five_yr_surv_table), alpha = 0.5))

```

```{r cox_model}
# build Cox model 
coxph(Surv(time = Time, event = Event) ~ Age + Gender + CRA + Tooth_Type + Jaw +
        Repair_Material + Surfaces + No_Surfaces + RCT + Crown_Type + Provider_Type,
      data = cmr) %>%
  # create table of results 
  tbl_regression(exp = TRUE, # this argument does the exponentiating step 
                 label = table1_labels) %>%
  bold_labels() %>%
  # format table 
  as_kable_extra(format = "latex",
                 booktabs= TRUE,
                 caption = "Table 5: Cox model results"
                 ) %>% 
  kable_styling(latex_options = c("HOLD_position", "striped"))
                 



```


# Figures



```{r timeline, fig.cap="Figure 1: Timeline chart"}
# Create a timeline chart 
set.seed(52246) # this means the same patients are chosen each time I run this code
example_patients <- sample(1:nrow(cmr), size = 5)

timelines <- ggplot(cmr[example_patients, ], aes(x = RecordID, y = Time)) + 
  geom_col(position = position_dodge(), width = 0.1, alpha = 0.5) +
  geom_point(data = cmr[example_patients, ],
             aes(RecordID, Time, color = Status, shape = Status),
             size = 6) + 
  labs(x = "Record ID") + 
  coord_flip() + 
  scale_color_viridis(discrete = TRUE) + 
  theme_bw() + 
  guides(colour = guide_legend(override.aes = list(size=4)))

(timelines)

```

```{r km_plot, fig.cap="Figure 2: Kaplan-Meier plot"}
# Kaplan Meier (KM) curve 

km1 <- survfit2(Surv(time = Time, event = Event) ~ 1, data = cmr) %>%
  ggsurvfit() +
  labs(
    x = "Years (after repair)",
    y = "Overall probability that repair is intact"
  )

# KM curve with confidence intervals and risk table 
km2 <- survfit2(Surv(time = Time, event = Event) ~ 1, data = cmr) %>% 
  ggsurvfit(
    theme = theme_ggsurvfit_KMunicate()
  ) +
  labs(
    x = "Years (after repair)",
    y = "Overall probability that repair is intact"
  ) + 
  add_confidence_interval(
    type = "ribbon",
    color = "#21918c",
    fill = "#21918c",
    alpha = 0.2
) + 
  add_risktable()

km2

```

```{r combined_plot, fig.cap="Figure 3: Median survival v. 3-year survival"}
km1 + 
  # visualize 3 year survival (green)
  geom_segment(x = 3, xend = 3,
               y = 0, yend = five_yr_surv$surv[2], 
               size = 1, 
               arrow = arrow(),
               aes(color = "3 year survival")) +
  geom_segment(x = 3, xend = 0,
               y = five_yr_surv$surv[2], yend = five_yr_surv$surv[2],
               size = 1, 
               arrow = arrow(length = unit(0.2, "inches")),
               aes(color = "3 year survival")) + 
  # visualize median survival time (blue)
geom_segment(x = s1_median["median"], xend = s1_median["median"],
             # the first y-val must be slightly > 0 for the arrow to print correctly
             y = 0.08, yend = 0.5,
             size = 1,
             arrow = arrow(ends = "first"),
             aes(color = "Median survival time")) + 
  geom_segment(x = 0, xend = s1_median["median"],
               y = 0.5, yend = 0.5,
               size = 1,
               arrow = arrow(ends = "last"),
               aes(color = "Median survival time")) + 
  # create manual legend 
  scale_color_manual(name='Measurement',
                     breaks=c('3 year survival', 'Median survival time'),
                     values=c('3 year survival'='#5ec962',
                              'Median survival time'='#21918c')) + 
  theme(legend.position = c(0.8, 0.8))


```

```{r compare_rct_groups, fig.cap="Figure 4: Comparing RCT groups", fig.width=7.5}
km3 <- survfit2(Surv(time = Time, event = Event) ~ RCT, data = cmr) 
km3 %>% 
  ggsurvfit() +
  labs(
    x = "Years (after repair)",
    y = "Overall probability that repair is intact"
  ) + 
  add_confidence_interval() + 
  add_risktable() + 
  scale_color_viridis(discrete = TRUE) + 
  scale_fill_viridis(discrete = TRUE) +
  theme_bw() + 
  annotate("text", x = 10, y = 0.75,
           label = glue::glue("{survfit2_p(km3)}"))
```

```{r compare_repair_groups, fig.cap="Figure 5: Comparing repair materials"}
km4 <- survfit2(Surv(time = Time, event = Event) ~ Repair_Material,
                # NB: we are considering only those repairs that were done with GI and Amalgam
                data = cmr %>% filter(Repair_Material %in% c("RMGI", "GI"))) 

km4 %>% 
  ggsurvfit() +
  labs(
    x = "Years (after repair)",
    y = "Overall probability that repair is intact"
  ) + 
  add_confidence_interval() + 
  add_risktable() + 
  scale_color_viridis(discrete = TRUE) + 
  scale_fill_viridis(discrete = TRUE) +
  theme_bw()  + 
  annotate("text", x = 7.5, y = 0.75, label = glue::glue("{survfit2_p(km4)}"))
```

