---
title: "Time to Event Analysis"
author: "Tabitha K. Peter"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE)
```

```{r source_calls}
source("R/R.R")
cmr <- read_csv("data/cmr.csv")
```


```{r data_prep}
# First look at the data 
# See what changes we need to make 
dplyr::glimpse(cmr) # notice: lots of options for 'clinic', and some categories are labeled as numbers! 
table(cmr$Clinic, useNA = "always") # hmmm... need to combine some categories 


# Make some formatting changes
cmr <- cmr %>%
  # collapse categories for clinic (we will need this for analysis)
  mutate(Clinic = if_else(Clinic %in% c("ADMS", "CCST", "CODHDG", "FEECLS", 
                                        "GMU", "HDGEN", "HDPROS", "LTDCAR"),
                          "Other",
                          Clinic),
         # tell the computer that 'No_surface' numbers represent *categories* 
         No_Surfaces = as.character(No_Surfaces),
         # tell the computer that RCT is a yes/no outcome
         RCT = case_when(
           RCT == 0 ~  "No RCT",
           RCT == 1 ~ "RCT"),
         # make the IDs have readable names 
         RecordID = paste0("Patient ", RecordID),
         # Represent the outcome (reintervention) in both numbers and words
         Event = Status, 
         Status = case_when(
           Event == 0 ~ "Censored",
           Event == 1 ~ "Event")) 

# Look at cleaned data 
kable(head(cmr),
      digits = 2,
      format = "pipe",
      caption = "Figure 1: A look at the data")


```


```{r descriptives}

# Create Table 1 
table1 <- tableby(~ .,
                  data = cmr %>%
                    dplyr::select(-c(RecordID, Event, No_Cases, Tooth_Number,
                                     Date_Repair, End_Date, Failure_Date)),
                  control = tableby.control(
                    test = FALSE
                  )
                  )

# Print out Table 1 in a readable format 
summary(table1) %>% 
  kable(digits = 2,
        format = "pipe",
        caption = "Table 1: Description of Data")





```


```{r timeline}
# Create a timeline chart 
set.seed(52246) # this means the same patients are chosen each time I run this code
example_patients <- sample(1:nrow(cmr), size = 5)

timelines <- ggplot(cmr[example_patients, ], aes(x = RecordID, y = Time)) + 
  geom_col(position = position_dodge(), width = 0.1, alpha = 0.5) +
  geom_point(data = cmr[example_patients, ],
             aes(RecordID, Time, color = Status, shape = Status),
             size = 6) + 
  coord_flip() + 
  scale_color_viridis(discrete = TRUE) + 
  theme_bw()


(timelines)

```



```{r km_plot}

# Kaplan Meier (KM) curve 
km1 <- survfit2(Surv(time = Time, event = Event) ~ 1, data = cmr) %>% 
  ggsurvfit() +
  labs(
    x = "Years (after repair)",
    y = "Overall probability that repair is intact"
  ) 
km1

# KM curve with confidence intervals and risk table 
km2 <- survfit2(Surv(time = Time, event = Event) ~ 1, data = cmr) %>% 
  ggsurvfit() +
  labs(
    x = "Years (after repair)",
    y = "Overall probability that repair is intact"
  ) + 
  add_confidence_interval() + 
  add_risktable()

km2

```

```{r median_survival}
s1 <- survfit(Surv(Time, Event) ~ 1, data = cmr)
summary(s1)$table[c("median", "0.95LCL", "0.95UCL")] %>%
  t() %>%
 kable(digits = 3,
       col.names = c(
         "Median survival time",
         "95% CI (lower)",
         "95% CI (upper)"
       ))
```

```{r nth_year_survival}
# one year survival -------------------------------------------------
one_yr_surv <- summary(survfit(Surv(Time, Event) ~ 1, data = cmr), times = 1)

nth_year_survival(one_yr_surv) %>% kable(digits = 3)

# 1 and 3 year survival ----------------------------------------------
three_yr_surv <- summary(survfit(Surv(Time, Event) ~ 1, data = cmr), times = c(1, 3))

nth_year_survival(three_yr_surv) %>% kable(digits = 3)

# visualize 3 year survival 
km1 + 
  geom_segment(x = 3, xend = 3,
               y = 0, yend = three_yr_surv$surv[2], 
               size = 1.5) +
  geom_segment(x = 3, xend = 0,
               y = three_yr_surv$surv[2], yend = three_yr_surv$surv[2],
               size = 1.5, 
               arrow = arrow(length = unit(0.2, "inches")))



# 1, 3, and 5 year survival -----------------------------------------------
five_yr_surv <- summary(survfit(Surv(Time, Event) ~ 1, data = cmr), times = c(1, 3, 5))

nth_year_survival(five_yr_surv) %>% kable(digits = 3)
```

```{r compare_groups}
km3 <- survfit2(Surv(time = Time, event = Event) ~ RCT, data = cmr) %>% 
  ggsurvfit() +
  labs(
    x = "Years (after repair)",
    y = "Overall probability that repair is intact"
  ) + 
  add_confidence_interval() + 
  add_risktable() + 
  scale_color_viridis(discrete = TRUE) + 
  scale_fill_viridis(discrete = TRUE) +
  theme_bw() 

km3
```



```{r cox_model}
coxph(Surv(time = Time, event = Event) ~ No_Cases + Age + Gender + CRA + Tooth_Type + Jaw + 
        Repair_Material + Surfaces + No_Surfaces + RCT + Crown_Type + Clinic +
        Provider_Type,
      data = cmr) %>% 
  tbl_regression(exp = TRUE) 


```

